name: Deploy Upload

on:
  push:
    branches:
      - main
    # paths:
    #   - ""
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Install Dependencies
        run: npm install
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: upload
          runtime: nodejs10
          region: us-west2
          credentials: ${{ secrets.gcp_credentials }} 
