name: Deploy JS

on:
  push:
    branches:
      - main
    # paths:
    #   - ""
jobs:
  javascript:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Install Dependencies
        working-directory: "server/functions/javascript"
        run: npm install
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: javascript
          runtime: nodejs10
          region: us-west2
          credentials: ${{ secrets.gcp_credentials }} 
          source_dir: "server/functions/javascript"
